- ['ir.actions.server', 'fields_lines', '']
- ['ir.server.object.lines', 'col1', '']
- ['ir.server.object.lines', 'evaluation_type', '']
- ['ir.server.object.lines', 'server_id', '']
- ['ir.server.object.lines', 'value', '']
- ['ir.ui.view', 'field_parent', '']
- ['res.company', 'base_onboarding_company_state', '']
- ['res.company', 'favicon', '']
