- ['project.milestone', 'message_main_attachment_id', '']
- ['project.project', 'alias_enabled', '']
- ['project.project', 'allow_recurring_tasks', '']
- ['project.project', 'allow_subtasks', '']
- ['project.project', 'message_main_attachment_id', '']
- ['project.project', 'partner_email', '']
- ['project.project', 'partner_phone', '']
- ['project.task', 'ancestor_id', '']
- ['project.task', 'display_project_id', '']
- ['project.task', 'email_from', '']
- ['project.task', 'fri', '']
- ['project.task', 'is_analytic_account_id_changed', '']
- ['project.task', 'is_blocked', '']
- ['project.task', 'is_closed', '']
- ['project.task', 'kanban_state', '']
- ['project.task', 'message_main_attachment_id', '']
- ['project.task', 'mon', '']
- ['project.task', 'partner_email', '']
- ['project.task', 'partner_phone', '']
- ['project.task', 'planned_hours', '']
- ['project.task', 'recurrence_update', '']
- ['project.task', 'repeat_day', '']
- ['project.task', 'repeat_month', '']
- ['project.task', 'repeat_number', '']
- ['project.task', 'repeat_on_month', '']
- ['project.task', 'repeat_on_year', '']
- ['project.task', 'repeat_week', '']
- ['project.task', 'repeat_weekday', '']
- ['project.task', 'sat', '']
- ['project.task', 'sun', '']
- ['project.task', 'thu', '']
- ['project.task', 'tue', '']
- ['project.task', 'wed', '']
- ['project.task.recurrence', 'fri', '']
- ['project.task.recurrence', 'mon', '']
- ['project.task.recurrence', 'next_recurrence_date', '']
- ['project.task.recurrence', 'recurrence_left', '']
- ['project.task.recurrence', 'repeat_day', '']
- ['project.task.recurrence', 'repeat_month', '']
- ['project.task.recurrence', 'repeat_number', '']
- ['project.task.recurrence', 'repeat_on_month', '']
- ['project.task.recurrence', 'repeat_on_year', '']
- ['project.task.recurrence', 'repeat_week', '']
- ['project.task.recurrence', 'repeat_weekday', '']
- ['project.task.recurrence', 'sat', '']
- ['project.task.recurrence', 'sun', '']
- ['project.task.recurrence', 'thu', '']
- ['project.task.recurrence', 'tue', '']
- ['project.task.recurrence', 'wed', '']
- ['project.task.type', 'auto_validation_kanban_state', '']
- ['project.task.type', 'legend_blocked', '']
- ['project.task.type', 'legend_done', '']
- ['project.task.type', 'legend_normal', '']
- ['project.update', 'message_main_attachment_id', '']
- ['res.company', 'analytic_plan_id', '']
