- ['ir.cron', 'doall', '']
- ['ir.cron', 'numbercall', '']
- ['ir.property', 'company_id', '']
- ['ir.property', 'fields_id', '']
- ['ir.property', 'name', '']
- ['ir.property', 'res_id', '']
- ['ir.property', 'type', '']
- ['ir.property', 'value_binary', '']
- ['ir.property', 'value_datetime', '']
- ['ir.property', 'value_float', '']
- ['ir.property', 'value_integer', '']
- ['ir.property', 'value_reference', '']
- ['ir.property', 'value_text', '']
- ['res.partner', 'date', '']
