- ['ir.translation', 'comments', '']
- ['ir.translation', 'lang', '']
- ['ir.translation', 'module', '']
- ['ir.translation', 'name', '']
- ['ir.translation', 'res_id', '']
- ['ir.translation', 'src', '']
- ['ir.translation', 'state', '']
- ['ir.translation', 'type', '']
- ['ir.translation', 'value', '']
