on:
  release:
    types:
      - published

name: release

jobs:
  pypi:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    environment: release

    permissions:
      # Used to authenticate to PyPI via OIDC.
      # Used to sign the release's artifacts with sigstore-python.
      id-token: write

      # Used to attach signing artifacts to the published release.
      contents: write

    steps:
    - uses: actions/checkout@v5

    - uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: build
      run: pipx run build

    - name: publish
      uses: pypa/gh-action-pypi-publish@release/v1
