name: test

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "master"
      - "master-ocabot-*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install
        run: |
          pip install pre-commit
          pip install -r test_requirements.txt
          pip install .
      - name: Run tests
        run: coverage run --source odoo_module_migrate -m pytest -v tests
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
